[package]
name = "creeper_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "*"
colored = "2.1.0"
serde_json = "*"
toml = "*"
lazy_static = "1.4.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3