[package]
name = "creeper_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
colored = "2.1.0"
serde_json = "1.0.128"
toml = "*"
lazy_static = "1.4.0"
unescape = "0.1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3